### PR TITLE
WIP: Use new Istio Ext Auth OAuth2-Proxy and add internal Dex

### PR DESCRIPTION
**Pull request by DavidSpek**
This PR configures OAuth2-Proxy with the new CUSTOM action for Envoy External Auth [see here](https://istio.io/latest/blog/2021/better-external-authz/). It also adds an internal Dex deployment for authentication. With this setup, it should be relatively easy to add Keycloak as a deployment option as well.

### CODE REVIEW

**Comment by springcoil** [comment]
Any update on this? We're trying to ship something at the moment and this is blocking us.

**Comment by DavidSpek** [comment]
This has been implemented in the branch https://github.com/argoflow/argoflow-aws/tree/feature/route53_certs_istio110. Note that the Dex config is not yet tested on AWS (I tested it on my local cluster) and the keycloak implementation is not yet finalized. However, the OAuth2-Proxy setup originally from this PR has been implemented and is working. I think we'll have that merged into master some time this week.

**Comment by DavidSpek** [comment]
I forgot to ask, is the internal Dex what is blocking you? Or just the OAtuh2-Proxy implementation?

**Comment by springcoil** [comment]
It's the Oauth2-proxy that we're waiting on. We had difficulties with that and I know the team (Aflorithmic Labs) spoke to you (I think it was you :) )

**Comment by springcoil** [comment]
Awesome looking forward to it being merged etc. :)

**Comment by DavidSpek** [comment]
Yeah, I'm not sure where those issues were coming from precisely. OAuth2-Proxy is already in master, but it is using EnvoyFilters and other resources for the authentication instead of the new CUSTOM action in Istio which makes the setup a bit cleaner (and hopefully more robust as Istio is managing the Envoy setup itself).

**Comment by DavidSpek** [comment]
This was merged in https://github.com/argoflow/argoflow-aws/pull/72

**Pull request closed without merging**
