### PR TITLE
Feature/certs 2

### PR DESCRIPTION
**Pull request by ncbkr**

### CODE REVIEW

**Comment by DavidSpek** [comment]
@ncbkr Does this PR just move the certs into a unified folder?

**Comment by ncbkr** [comment]
@DavidSpek yes that's a precise description of what is going on. Do you have any comments?

**Comment by DavidSpek** [comment]
@ncbkr Nope, just wanted to check and make sure it is what it seemed to be. I'm just busy working through the steps needed to integrate namespace based Grafana dashboards integrated with the kubeflow OAuth workflow (and without running multiple Grafana instances). Once I get that done I'll do some small cleanups for this PR and merge it.

Thanks for the contribution!

BTW, are you on the Kubeflow Slack? Might be handy if we need to discuss some things.

**Comment by ncbkr** [comment]
okay cool. If you have any questions / feedback, I am happy to discuss. I will join slack and get back to you

**Comment by DavidSpek** [comment]
@ncbkr Sorry it took a bit longer. Would you like to go over the small fixes I did before I merge this PR?

**Comment by ncbkr** [comment]
@DavidSpek no worries. I had a look at the changes you made. looks good to me. Only one question out of interest. You removed the `resources` directory in `certificates/imported`. I am fine with it but interested in the reasoning behind this change.

**Pull request merged**
